version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - /postgres-data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gui@alura.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres

  # Serviço da sua aplicação
  app:
    build: .
    ports:
      - "8000:8000"  # Expondo a porta 8000 para fora do container
    depends_on:
      - postgres  # Se a sua aplicação depende do PostgreSQL
    volumes:
      - .:/app  # Mapeando o diretório atual para o diretório /app no container

